# Generated by Django 4.1.7 on 2023-03-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_colors_cpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colors',
            name='cpath',
        ),
        migrations.AddField(
            model_name='colors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
